flat_compile_qmd_course.Rmd:
  path: dev/flat_compile_qmd_course.Rmd
  state: active
  R:
  - R/compile_qmd_course.R
  - R/render_single_qmd.R
  tests:
  - tests/testthat/test-compile_qmd_course.R
  - tests/testthat/test-render_single_qmd.R
  vignettes: vignettes/compile-n-qmd-to-html.Rmd
  inflate:
    flat_file: dev/flat_compile_qmd_course.Rmd
    vignette_name: Compile n qmd to html
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_utils.Rmd:
  path: dev/flat_utils.Rmd
  state: active
  R:
  - R/clean_rendering_files.R
  - R/create_template_html.R
  - R/extract_html_slides.R
  tests:
  - tests/testthat/test-extract_html_slides.R
  - tests/testthat/test-create_template_html.R
  - tests/testthat/test-clean_rendering_files.R
  vignettes: []
  inflate:
    flat_file: dev/flat_utils.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
keep:
  path: keep
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
