---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# my_fun

```{r function-my_fun}
#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
compile_course <- function(
    vec_qmd_path,
    ...
) {
  
}
```

```{r examples-my_fun}

courses_path <- system.file(
  "courses",
  package = "nq1h"
)

qmds <- list.files(
  path = courses_path, 
  full.names = TRUE, 
  pattern = "qmd$"
)

vec_qmd_path <- qmds

temp_dir <- tempfile(pattern = "compile") 
dir.create(temp_dir)

file.copy(
  from = vec_qmd_path,
  to = temp_dir
)

withr::with_dir(
  temp_dir,
  {
    qmds <- list.files(
      path = temp_dir, 
      full.names = TRUE, 
      pattern = "qmd$"
    )
    for (qmd in vec_qmd_path){
      cli::cat_bullet(
        sprintf("Rendering %s", basename(qmd))
      )
      output_file <- sub("^(.+)\\.qmd$", "\\1.html", basename(qmd))
      quarto::quarto_render(
        input = qmd,
        output_file = output_file,
        quiet = FALSE
      )
      
    }
  }
)

template_qmd <- readLines(
  system.file(
    "template.qmd",
    package = "nq1h"
  )
)

path_html_files <- list.files(
  temp_dir, 
  full.names = TRUE,
  pattern = "\\.html$"
)

divs_to_insert <- path_html_files |> 
  lapply(
    \(path_html_file) {
      sprintf(
        '<div data-external-replace="%s">  </div>',
        path_html_file
      )
    }
  ) |> 
  paste(
    collapse = "\n\n---\n\n"
  )

index_qmd <- gsub(
  pattern = "\\{\\{insert_divs\\}\\}",
  replacement = divs_to_insert,
  template_qmd
) 

writeLines(
  index_qmd,
  "index.qmd"
)

```

```{r tests-my_fun}
test_that("my_fun works", {
  
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Go further")
```

