# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

test_that("clean_rendering_files works", {
  # create a temp dir with qmd
  temp_dir <- tempfile(pattern = "clean")
  
  dir.create(
    path = file.path(temp_dir, "img"),
    recursive = TRUE
  )
  
  file.copy(
    from = system.file("courses", "C01", "qmd1_for_test.qmd", package = "nq1h"),
    to = temp_dir
  )
  
  file.copy(
    from = system.file("courses", "C01", "img", "logo_1.png", package = "nq1h"),
    to = file.path(temp_dir, "img")
  )
  
  # list files before rendering
  file_and_dirs_before <- list.files(
    temp_dir,
    recursive = TRUE,
    full.names = TRUE,
    include.dirs = TRUE
  )
  
  # render qmd
  quarto::quarto_render(
    input = file.path(temp_dir, "qmd1_for_test.qmd"),
    quiet = TRUE
  )
  
  # remove created files and dirs
  clean_rendering_files(
    dir = temp_dir,
    present_before = file_and_dirs_before
  )
  
  # test list of files is the same before and after
  file_present_now <- list.files(
    temp_dir,
    recursive = TRUE,
    full.names = TRUE,
    include.dirs = TRUE
  )
  
  expect_setequal(
    object = file_present_now,
    expected = file_and_dirs_before)
  
  # clean temp dir
  unlink(temp_dir, recursive = TRUE)
})
