# WARNING - Generated by {fusen} from dev/flat_html_to_pdf.Rmd: do not edit by hand

test_that("convert_html_to_pdf() produces a pdf", {
  
  skip_on_ci()
  
  temp_dir <- tempfile(pattern = "compile")
  
  courses_path <- system.file(
    "courses",
    package = "nq1h"
  )
  qmds <- list.files(
    path = courses_path,
    full.names = TRUE,
    recursive = TRUE,
    pattern = "qmd$"
  )
  
  html_output <- compile_qmd_course(
    vec_qmd_path = qmds,
    output_dir = temp_dir,
    output_html = "complete_course.html"
  )
  
  file_path <- list(
    html = file.path(temp_dir, "complete_course.html"),
    pdf = file.path(temp_dir, "complete_course.pdf")
  )
  
  convert_html_to_pdf(
    html_path = file_path$html,
    pdf_path = file_path$pdf
  )
  
  expect_true(
    file.exists(file_path$pdf)
  )
  
  unlink(temp_dir, TRUE, TRUE)
})

test_that("Error if html file does not exist", {
  expect_error(
    convert_html_to_pdf(
      html_path = "foo.html"
    )
  )
})

test_that("Error if debug_dry_run not a logical", {
  temp_html <- tempfile(fileext = ".html")
  file.create(temp_html)
  
  expect_error(
    convert_html_to_pdf(
      html_path = temp_html,
      pdf_path = "foo.pdf",
      debug_dry_run = "A String!"
    )
  )
  
  unlink(temp_html)
})

test_that("Error if pause_before_slide_export is not a positive number", {
    temp_html <- tempfile(fileext = ".html")
  file.create(temp_html)
  
  expect_error(
    convert_html_to_pdf(
      html_path = temp_html,
      pdf_path = "foo.pdf",
      pause_before_slide_export = TRUE
    )
  )
  
  unlink(temp_html)
})
