# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

# create temp dir
temp_dir <- tempfile(pattern = "template")

test_that("create_template_html generate an html with proper title and theme", {

  # create html template
  path_to_html_template <- create_template_html(
    path_to_qmd = system.file("template.qmd", package = "nq1h"),
    output_dir = temp_dir,
    output_file = "complete_course.html"
  )
  
  # list files in extensions
  expect_extension_files <- list.files(
    file.path(temp_dir, "_extensions"),
    recursive = TRUE
  )
  
  # extract html content
  slide_content <- path_to_html_template |>
    read_html() |>
    html_elements(css = ".slides") |>
    html_children() |>
    as.character()
  
  #' @description test quakr extension dir is correctly copied
  expect_setequal(
    object = expect_extension_files,
    expected = c(
      "ThinkR-open/thinkridentity/_extension.yml",
      "ThinkR-open/thinkridentity/background.png",
      "ThinkR-open/thinkridentity/logo.png",
      "ThinkR-open/thinkridentity/logo.svg",
      "ThinkR-open/thinkridentity/thinkridentity.scss"
    )
  )
  
  #' @description test html content of template has correct theme and title
  expect_snapshot(x = slide_content)
  
})

# clean up
unlink(temp_dir, recursive = TRUE)
