# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("add_compil_profile_and_extension works", {
  # add two qmd in a tmp dir, one with yaml project
  tmpdir <- tempfile(pattern = "addcompil")
  dir.create(file.path(tmpdir, "tmpsubfolder1"), recursive = TRUE)
  dir.create(file.path(tmpdir, "tmpsubfolder2"), recursive = TRUE)
  
  vec_qmd_path <- c(
    file.path(tmpdir, "tmpsubfolder1", "dummy1.qmd"),
    file.path(tmpdir, "tmpsubfolder2", "dummy2.qmd")
  )
  
  file.create(vec_qmd_path)

  #' @description test function stops if not project is found
  expect_error(
    {new_proj_files <- add_compil_profile_and_extension(vec_qmd_path = vec_qmd_path, quiet = FALSE)},
    regexp = "No quarto project found."
  ) |> 
    expect_message(regexp = "No quarto project found")
  
  # add quarto project
  file.create(
    file.path(tmpdir, "_quarto.yaml")
  )
  
  #' @description test function add compil and quakr
  new_proj_files <- add_compil_profile_and_extension(vec_qmd_path = vec_qmd_path, quiet = FALSE)
  
  #' @description test project files are created if not pre existing
  expect_true(all(file.exists(new_proj_files)))
  
  #' @description test user message are sent for compil and quakr theme
  expect_message(
    {new_proj_files <- add_compil_profile_and_extension(vec_qmd_path = vec_qmd_path, quiet = FALSE)},
    regexp = "Using it for compil."
  ) |> 
    expect_message(regexp = "Using it for compil.")
  
  #' @description test project files are not created if pre-existing
  expect_equal(object = new_proj_files, expected = c("NULL", "NULL"))
  
  # cleanup
  unlink(tmpdir, recursive = TRUE)
})
