# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

test_that("create_template_html works", {

  # create temp dir
  temp_dir <- tempfile(pattern = "template")
  
  # create html template
  path_to_html_template <- create_template_html(
    path_to_qmd = system.file("template.qmd", package = "nq1h"),
    output_dir = temp_dir,
    output_file = "complete_course.html"
  )

  # test extension dir is correctly copied
  expect_md5 <- tools::md5sum(
    files = list.files(
      system.file(
        "_extensions",
        package = "nq1h"
      ),
      recursive = TRUE,
      full.names = TRUE
    )
  )
  
  observed_md5 <- tools::md5sum(
    files = list.files(
      file.path(temp_dir, "_extensions"),
      recursive = TRUE,
      full.names = TRUE
    )
  )
  
  expect_true(all(expect_md5 == observed_md5))
  
  # test html content of template
  slide_content <- path_to_html_template |>
    read_html() |>
    html_elements(css = ".slides") |>
    html_children() |>
    as.character()
  
  expect_equal(
    object = slide_content,
    expected = c(
      "<section id=\"title-slide\" data-background-image=\"_extensions/thinkridentity/font.png\" class=\"quarto-title-block center\"><h1 class=\"title\">Formation R</h1>\n\n<div class=\"quarto-title-authors\">\n</div>\n\n</section>",
      "<section class=\"slide level2\"><p>{{ include_html_content }}</p>\n\n<img src=\"_extensions/thinkridentity/thinkr_logo.png\" class=\"slide-logo r-stretch\"><div class=\"footer footer-default\">\n<p><strong><i class=\"las la-book\"></i> Formation R</strong> | Retrouvez nous sur <a href=\"https://thinkr.fr\" class=\"uri\">https://thinkr.fr</a></p>\n</div>\n</section>"
    )
  )
  
  # clean up
  unlink(temp_dir, recursive = TRUE)
  
})
