# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

test_that("add_companion_folder works", {
  # create tmp dir
  temp_dir <- tempfile(pattern = "compile")
  dir.create(temp_dir, recursive = TRUE)
  
  # copy html and plugin dir
  file.copy(
    from = system.file("template.html", package = "nq1h"),
    to = temp_dir
  )
  
  file.copy(
    from = system.file("plugin", package = "nq1h"),
    to = temp_dir,
    recursive = TRUE
  )
  
  # test with wrong arguments
  expect_error(object = {
    add_companion_folder(
      html_path = file.path(temp_dir, "template.html"),
      src_regex = "__path_to_deps_folder__",
      from_lib = file.path(temp_dir, "plugin"),
      to_lib = "another/dir/path"
    )
  }, regexp = "The lib folder path should be a descendant of html folder path")
  
  # run add_companion_folder()
  expect_message(
    object = {
      add_companion_folder(
        html_path = file.path(temp_dir, "template.html"),
        src_regex = "__path_to_deps_folder__",
        from_lib = file.path(temp_dir, "plugin"),
        to_lib = file.path(temp_dir, "plugin_copy", "plugin")
      )
    },
    regexp = "Paths to dependencies will be edited in 27 lines of the final HTML."
  )
  
  # test content of lib
  md5_before <- tools::md5sum(files = list.files(
    path = file.path(
      temp_dir,
      "plugin"
    ),
    full.names = TRUE
  ))
  
  md5_after <- tools::md5sum(files = list.files(
    path = file.path(
      temp_dir,
      "plugin_copy",
      "plugin"
    ),
    full.names = TRUE
  ))
  
  expect_true(
    all(md5_before == md5_after)
  )
  
  # test no missed paths in html
  html_content <- readLines(file.path(temp_dir, "template.html"))
  fetch_temp_path <- grepl(
    pattern = temp_dir,
    x = html_content
  )
  fetch_initial_path <- grepl(
    pattern = "__path_to_deps_folder__",
    x = html_content
  )
  expect_true(!any(fetch_initial_path, fetch_temp_path))
  
  # clean up
  unlink(temp_dir, recursive = TRUE)
})
