# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

test_that("compile_qmd_course works", {
  # list example qmds
  courses_path <- system.file("courses",
                              package = "nq1h")
  
  qmds <- list.files(path = courses_path,
                     full.names = TRUE,
                     pattern = "qmd$")
  
  # generate html in temp folder
  temp_dir <- tempfile(pattern = "compile")
  
  compile_qmd_course(vec_qmd_path = qmds,
                     output_dir = temp_dir)
  
  # test that html file exists
  expected_html <- file.path(temp_dir,
                             gsub(".qmd", ".html", basename(qmds)))
  expect_true(all(file.exists(expected_html)))
  
  # test that companion html folders exist
  expected_html_folders <- gsub(".html", "_files", expected_html)
  expect_true(all(file.exists(expected_html_folders)))
  
  # clean up
  unlink(temp_dir, recursive = TRUE)
})
