# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

# create temp dir
temp_dir <- tempfile(pattern = "template")

test_that("create_template_html generate an html with proper title and theme", {

  # create html template
  path_to_html_template <- create_template_html(
    path_to_qmd = system.file("template.qmd", package = "nq1h"),
    output_dir = temp_dir,
    output_file = "complete_course.html"
  )
  
  # list files in extensions
  expect_extension_files <- list.files(
    file.path(temp_dir, "_extensions"),
    recursive = TRUE
  )
  
  # extract html content
  slide_content <- path_to_html_template |>
    read_html() |>
    html_elements(css = ".slides") |>
    html_children() |>
    as.character()
  
  #' @description test quakr extension dir is correctly copied
  expect_setequal(
    object = expect_extension_files,
    expected = c(
      "thinkridentity/_extension.yml",
      "thinkridentity/background.png",
      "thinkridentity/logo.png",
      "thinkridentity/logo.svg",
      "thinkridentity/thinkridentity.scss"
    )
  )
  
  #' @description test html content of template has correct theme and title
  expect_equal(
    object = slide_content,
    expected = c(
      "<section id=\"title-slide\" data-background-image=\"_extensions/thinkridentity/background.png\" class=\"quarto-title-block center\"><h1 class=\"title\">Formation R</h1>\n  <p class=\"subtitle\">01/01/01-01/01/01</p>\n\n<div class=\"quarto-title-authors\">\n</div>\n\n</section>",
      "<section class=\"slide level2\"><p>{{ include_html_content }}</p>\n</section>",
      "<section id=\"include_trainer\" class=\"slide level2\"><h2>{{ include_trainer }}</h2>\n<p><strong>{{ include_phone }}</strong></p>\n<p><strong>{{ include_mail }}</strong></p>\n\n<img src=\"_extensions/thinkridentity/logo.png\" class=\"slide-logo r-stretch\"><div class=\"footer footer-default\">\n<p><strong><i class=\"las la-book\"></i> Formation R</strong> | Retrouvez nous sur <a href=\"https://thinkr.fr\" class=\"uri\">https://thinkr.fr</a></p>\n</div>\n</section>"
    )
  )
  
})

# clean up
unlink(temp_dir, recursive = TRUE)
