# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' add_companion_folder
#'
#' Copy a lib folder and solve dependencies path in html
#'
#' @param html_path character. Path to the html file to be edited, serve as the root for lib folder paths
#' @param src_regex character. Regex of the existing lib path in the html to replace with new location
#' @param from_lib character. Path to the lib folder to copy
#' @param to_lib character. Path to copy to lib folder to.
#'
#' @importFrom cli cli_alert_info
#'
#' @return NULL. 2nd effect : create a lib folder and edit html path accordingly
#'
#' @export
#' @examples
#' # create tmp dir
#' temp_dir <- tempfile(pattern = "compile")
#' dir.create(temp_dir, recursive = TRUE)
#' 
#' # copy html and plugin dir
#' file.copy(
#'   from = system.file("template.html", package = "nq1h"),
#'   to = temp_dir
#' )
#' 
#' file.copy(
#'   from = system.file("plugin", package = "nq1h"),
#'   to = temp_dir,
#'   recursive = TRUE
#' )
#' 
#' # run add_companion_folder()
#' add_companion_folder(
#'   html_path = file.path(temp_dir, "template.html"),
#'   src_regex = "__path_to_deps_folder__",
#'   from_lib = file.path(temp_dir, "plugin"),
#'   to_lib = file.path(temp_dir, "plugin_copy", "plugin")
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
add_companion_folder <- function(
    html_path,
    src_regex,
    from_lib,
    to_lib
) {
  # verify lib dir will be created as a sub-folder of html dir
  html_root_dir <- dirname(normalizePath(html_path))
  
  lib_is_inside_root <- grepl(
    pattern = html_root_dir,
    x = normalizePath(to_lib)
  )
  
  if (!lib_is_inside_root) {
    stop("The lib folder path should be a descendant of html folder path")
  }
  
  # copy lib dir
  if (!file.exists(to_lib)) {
    dir.create(to_lib, recursive = TRUE)
  }
  
  file.copy(
    from = file.path(from_lib, "."),
    to = to_lib,
    recursive = TRUE
  )
  
  # detect lib path in html
  html_content <- readLines(html_path)
  
  n_path <- sum(grepl(pattern = src_regex,
                      x = html_content))
  
  cli_alert_info(
    "Paths to dependencies will be edited in {n_path} line{?s} of the final HTML."
  )
  
  # create replacement path as a relative path to html file
  lib_path_edited <- gsub(
    pattern = paste0(html_root_dir, "/"),
    replacement = "",
    x = normalizePath(to_lib)
  )
  
  # replace path in html
  html_content_edited_path <- gsub(
    pattern = src_regex,
    replacement = lib_path_edited,
    x = html_content
  )
  
  # overwrite html with new path
  write(
    x = html_content_edited_path,
    file = html_path
  )
  
  return(NULL)
}
