# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Detect quarto project and add a temporary compil profile
#' 
#' @param vec_qmd_path character. Path to the qmd files targeted for compilation
#' @param quiet logical. Warn user of project status.
#' 
#' @importFrom quarto quarto_inspect
#' @importFrom cli cli_alert_info
#' @importFrom purrr map map_lgl
#' 
#' @return Create file path. Side effect : create a yaml compil profile.
#' 
#' @noRd
#' @examples
#' # add a qmd in a tmp dir
#' tmpdir <- tempfile(pattern = "addcompil")
#' dir.create(tmpdir)
#'
#' qmd <- file.path(tmpdir, "dummy.qmd")
#' file.create(qmd)
#' file.create(file.path(tmpdir, "_quarto.yaml"))
#'
#' # init a quarto project
#' add_compil_profile_and_extension(vec_qmd_path = qmd, quiet = FALSE)
#'
#' # detects pre-existing
#' add_compil_profile_and_extension(vec_qmd_path = qmd, quiet = FALSE)
#'
#' # cleanup
#' unlink(tmpdir, recursive = TRUE)
add_compil_profile_and_extension <- function(
  vec_qmd_path,
  quiet = FALSE
  ){
  
  # look for existing quarto projects
  qmd_dir <- dirname(vec_qmd_path)
  
  quarto_proj <- map(
    .x = vec_qmd_path,
    .f = \(x){quarto_inspect(x)$project$dir}
    )
  
  no_quarto_proj <- map_lgl(quarto_proj, is.null)
  qmd_dir_with_no_proj <- unique(qmd_dir[no_quarto_proj])
  qmd_dir_with_proj <- unique(quarto_proj[!no_quarto_proj])
  
  # stop if qmd are not part of a quarto project
  if (length(qmd_dir_with_no_proj) > 0){
    if (!quiet){
    cli_alert_danger(
      paste("No quarto project found for {qmd_dir_with_no_proj}.",
            "Stopping execution.",
            "To setup a quarto project, please visit {.url https://quarto.org/docs/projects/quarto-projects.html}")
      )
    }
    stop("No quarto project found.")
  }

  # add profile and extension in detected projects
  if (length(qmd_dir_with_proj) > 0){
    
    # add a compil profile
    quarto_compil_added <- file.path(
      qmd_dir_with_proj,
      "_quarto-compil.yml"
      )
    
    copied_compil <- map(
      .x = quarto_compil_added,
      .f = \(x){
        copy_if_not_already_exist(
          from = system.file("_quarto-compil.yml", package = "squash"),
          to = x,
          copy_type = "file"
        )
      }
    )

    # add quakr extension
    quarto_quakr_added <- file.path(
      qmd_dir_with_proj,
      "_extensions",
      "ThinkR-open"
    )
    
    copied_quakr <- map(
      .x = quarto_quakr_added,
      .f = \(x){
        copy_if_not_already_exist(
          from = system.file("_extensions",
                             "ThinkR-open",
                             package = "squash"),
          to = x,
          copy_type = "dir"
        )
      }
    )
  }
  
  # return list of created files
  copied_files <- as.character(c(copied_compil, copied_quakr))
  return(copied_files)
}
