# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' Independently compile several qmd and create a common html
#'
#' @param vec_qmd_path character. Vector of the path to qmd files
#' @param output_dir character. Output path to store html files and companion folders
#' @param output_html character. File name of the complete html output saved
#' 
#' @importFrom tools file_ext
#' @importFrom withr with_dir
#' @importFrom cli cat_bullet
#' @importFrom quarto quarto_render
#' @importFrom htmltools htmlTemplate renderDocument save_html
#' 
#' @return character. The path to the resulting html file
#' 
#' @export
#' @examples
#' # list example qmds
#' courses_path <- system.file(
#'   "courses",
#'   package = "nq1h"
#' )
#' 
#' qmds <- list.files(
#'   path = courses_path, 
#'   full.names = TRUE, 
#'   pattern = "qmd$"
#' )
#' 
#' # generate html in temp folder
#' temp_dir <- tempfile(pattern = "compile") 
#' 
#' html_output <- compile_qmd_course(
#'   vec_qmd_path = qmds,
#'   output_dir = temp_dir,
#'   output_html = "course_complete.html"
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
#' 
compile_qmd_course <- function(
    vec_qmd_path,
    output_dir,
    output_html
) {
  # check paths
  not_all_files_are_qmd <- any(
      file_ext(vec_qmd_path) != "qmd"
    )
  if (isTRUE(not_all_files_are_qmd)){
    stop("Some of the input files are not qmd files.")
  }

  # create output dir
  if (isFALSE(file.exists(output_dir))){
    dir.create(output_dir)
  }

  # copy qmd to render dir
  file.copy(
    from = vec_qmd_path,
    to = output_dir
  )

  # render qmd to html
  with_dir(
    output_dir,
    {
      for (qmd in basename(vec_qmd_path)){
        cat_bullet(
          sprintf("Rendering %s", qmd)
        )
        quarto_render(
          input = qmd,
          quiet = FALSE
        )
      }
    }
  )
  
  # remove qmd from render dir
  unlink(file.path(output_dir, basename(vec_qmd_path)))
  
  # read html and extract slides elements
  vec_html_path <- file.path(output_dir,
                             gsub(".qmd", ".html", basename(vec_qmd_path)))
  
  html_content <- extract_html_slides(
    vec_html_path = vec_html_path
    )
  
  # include content in template
  complete_html <- htmlTemplate(
    filename = system.file("template.html", package = "nq1h"),
    include_html_content = html_content
  ) |>
    renderDocument()
  
  # save html file
  path_to_html <- file.path(output_dir,
                            output_html)
  
  save_html(html = complete_html,
            file = path_to_html,
            libdir = file.path(output_dir, "lib"))

  return(path_to_html)
}
