# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' compile_qmd_course
#'
#' Independently compile several qmd and create a common html
#'
#' @param vec_qmd_path character. Vector of the path to qmd files
#' @param output_dir character. Output path to store html files and companion folders
#' @param output_html character. File name of the complete html output saved
#'
#' @importFrom tools file_ext
#' @importFrom withr with_dir
#' @importFrom cli cat_bullet
#' @importFrom quarto quarto_render
#' @importFrom htmltools htmlTemplate renderDocument save_html
#'
#' @return character. The path to the resulting html file
#'
#' @export
#' @examples
#' # list example qmds
#' courses_path <- system.file(
#'   "courses",
#'   package = "nq1h"
#' )
#' 
#' qmds <- list.files(
#'   path = courses_path,
#'   full.names = TRUE,
#'   pattern = "qmd$"
#' )
#' 
#' # generate html in temp folder
#' temp_dir <- tempfile(pattern = "compile")
#' 
#' html_output <- compile_qmd_course(
#'   vec_qmd_path = qmds,
#'   output_dir = temp_dir,
#'   output_html = "course_complete.html"
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
compile_qmd_course <- function(
    vec_qmd_path,
    output_dir,
    output_html
) {
  # check paths
  not_all_files_are_qmd <- any(
    file_ext(vec_qmd_path) != "qmd"
  )
  if (isTRUE(not_all_files_are_qmd)) {
    stop("Some of the input files are not qmd files.")
  }
  
  # create output dir
  if (isFALSE(file.exists(output_dir))) {
    dir.create(output_dir)
  }
  
  # copy qmd to render dir
  file.copy(
    from = vec_qmd_path,
    to = output_dir
  )
  
  # render qmd to html
  vec_qmd_filename <- basename(vec_qmd_path)
  
  with_dir(
    output_dir,
    {
      for (qmd in vec_qmd_filename) {
        cat_bullet(
          sprintf("Rendering %s", qmd)
        )
        quarto_render(
          input = qmd,
          quiet = FALSE
        )
      }
    }
  )
  
  # remove qmd from render dir
  unlink(file.path(
    output_dir,
    vec_qmd_filename
  ))
  
  # read html and extract slides elements
  vec_html_path <- file.path(
    output_dir,
    gsub(".qmd", ".html", vec_qmd_filename)
  )
  
  html_content <- extract_html_slides(
    vec_html_path = vec_html_path
  )
  
  # include content in template
  complete_html <- htmlTemplate(
    filename = system.file("template.html",
                           package = "nq1h"),
    include_html_content = html_content
  ) |>
    renderDocument()
  
  # save html file
  path_to_html <- file.path(
    output_dir,
    output_html
  )
  
  save_html(
    html = complete_html,
    file = path_to_html,
    libdir = file.path(output_dir, "lib")
  )
  
  # copy lib folder from 1st render and edit paths in html
  path_to_lib_folder <- gsub(".html", "_files", vec_html_path[[1]])
  
  add_companion_folder(
    html_path = path_to_html,
    src_regex = "__path_to_deps_folder__",
    from_lib = path_to_lib_folder,
    to_lib = gsub(".html", "_files", path_to_html)
  )
  
  return(path_to_html)
}
