# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' Independently compile several qmd and create a common html
#'
#' @param vec_qmd_path character. Vector of the path to qmd files
#' @param output_dir character. Output path to store html files and companion folders
#' 
#' @importFrom tools file_ext
#' @importFrom withr with_dir
#' @importFrom cli cat_bullet
#' @importFrom quarto quarto_render
#' 
#' @return NULL Side effect : generate html files in output dir
#' 
#' @export
#' @examples
#' # list example qmds
#' courses_path <- system.file(
#'   "courses",
#'   package = "nq1h"
#' )
#' 
#' qmds <- list.files(
#'   path = courses_path, 
#'   full.names = TRUE, 
#'   pattern = "qmd$"
#' )
#' 
#' # generate html in temp folder
#' temp_dir <- tempfile(pattern = "compile") 
#' 
#' compile_qmd_course(
#'   vec_qmd_path = qmds,
#'   output_dir = temp_dir
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
#' 
#' #---- to refactor next
#' 
#' # template_qmd <- readLines(
#' #   system.file(
#' #     "template.qmd",
#' #     package = "nq1h"
#' #   )
#' # )
#' # 
#' # path_html_files <- list.files(
#' #   temp_dir, 
#' #   full.names = TRUE,
#' #   pattern = "\\.html$"
#' # )
#' # 
#' # divs_to_insert <- path_html_files |> 
#' #   lapply(
#' #     \(path_html_file) {
#' #       sprintf(
#' #         '<div data-external-replace="%s">  </div>',
#' #         path_html_file
#' #       )
#' #     }
#' #   ) |> 
#' #   paste(
#' #     collapse = "\n\n---\n\n"
#' #   )
#' # 
#' # index_qmd <- gsub(
#' #   pattern = "\\{\\{insert_divs\\}\\}",
#' #   replacement = divs_to_insert,
#' #   template_qmd
#' # ) 
#' # 
#' # writeLines(
#' #   index_qmd,
#' #   "index.qmd"
#' # )
#' 
compile_qmd_course <- function(
    vec_qmd_path,
    output_dir
) {
  # check paths
  not_all_files_are_qmd <- any(
      file_ext(vec_qmd_path) != "qmd"
    )
  if (isTRUE(not_all_files_are_qmd)){
    stop("Some of the input files are not qmd files.")
  }

  # create output dir
  if (isFALSE(file.exists(output_dir))){
    dir.create(output_dir)
  }

  # copy qmd to render dir
  file.copy(
    from = vec_qmd_path,
    to = output_dir
  )

  # render qmd to html
  with_dir(
    output_dir,
    {
      for (qmd in basename(vec_qmd_path)){
        cat_bullet(
          sprintf("Rendering %s", qmd)
        )
        quarto_render(
          input = qmd,
          quiet = FALSE
        )
      }
    }
  )
  
  # remove qmd from render dir
  unlink(file.path(output_dir, basename(vec_qmd_path)))

  return(NULL)
}
