# WARNING - Generated by {fusen} from dev/flat_html_to_pdf.Rmd: do not edit by hand

#' Convert a html presentation to pdf
#' 
#' This function is an interface to the dockerised version of `decktape`
#' a cli pdf exporter written in JavaScript. 
#' See  https://github.com/astefanutti/decktape/
#' 
#' It requires that:
#' * docker is installed on the system
#' * the user running the command is part of the docker group
#' 
#' @param html_path A character. Path to html file.
#' @param pdf_path A character. Path to pdf file.
#' @param debug_dry_run A logical. If TRUE the docker command string is returned without running it.
#' @param pause_before_slide_export A positive integer. Number of milliseconds to wait before to export each slide.
#'
#' @return Nothing. Used for its side effect.
#' 
#' @importFrom  cli cat_rule
#' 
#' @export
#' @examples
#' temp_dir <- tempfile(pattern = "compile")
#'
#' courses_path <- system.file(
#'   "courses",
#'   package = "nq1h"
#' )
#' qmds <- list.files(
#'   path = courses_path,
#'   full.names = TRUE,
#'   recursive = TRUE,
#'   pattern = "qmd$"
#' )
#'
#' html_output <- compile_qmd_course(
#'   vec_qmd_path = qmds,
#'   output_dir = temp_dir,
#'   output_html = "complete_course.html"
#' )
#'
#' file_path <- list(
#'   html = file.path(temp_dir, "complete_course.html"),
#'   pdf = file.path(temp_dir, "complete_course.pdf")
#' )
#'
#' convert_html_to_pdf(
#'   html_path = file_path$html,
#'   pdf_path = file_path$pdf
#' )
#'
#' # browseURL(file_path$pdf)
#'
#' unlink(temp_dir, TRUE, TRUE)
convert_html_to_pdf <- function(
    html_path,
    pdf_path,
    pause_before_slide_export = 10,
    debug_dry_run = FALSE
) {

  stopifnot(
    file.exists(html_path)
  )  
  stopifnot(
    is.numeric(pause_before_slide_export) &&
      pause_before_slide_export > 0 
  )
  stopifnot(
    is.logical(debug_dry_run)
  )
  
  # Use absolute file paths so that docker command outcome
  # does not on current working directory
  html_path_directory <- normalizePath(
    dirname(html_path)
  )
  pdf_path_directory <- normalizePath(
    dirname(pdf_path)
  )
  
  docker_image <- "astefanutti/decktape"
  docker_command <- paste(
    "docker run --rm -t",
    # Directory where the pdf file will be saved
    sprintf("-v %s:/slides", pdf_path_directory),
    # Directory where the html file is
    sprintf("-v %s:/home/user", html_path_directory),
    docker_image,
    # html file name
    sprintf("/home/user/%s", basename(html_path)),
    # Pdf file name
    basename(pdf_path),
    # Time in ms before recording slide
    sprintf("--pause=%s", pause_before_slide_export)
  )
  
  if (
    isTRUE(debug_dry_run)
  ) {
    return(docker_command)
  }
  
  cat_rule(
    "Running external docker service: decktape"
  )
  system(docker_command)
}
