# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Copy file or directory if they do not already exist
#' 
#' @param from character. The file or directory to copy
#' @param to character. The target path to copy to
#' @param copy_type character. The type of element to copy (file or dir)
#' @param quiet logical. Should the use be warned about pre-existing file/dir
#' 
#' @return character. Path of added file or directory.
#' 
#' @noRd
#' @examples
#' tmpdir <- tempfile(pattern = "copy")
#'
#' copy_if_not_already_exist(
#'   from = system.file("_extensions","ThinkR-open","thinkridentity", package = "squash"),
#'   to = file.path(tmpdir, "thinkridentity"),
#'   copy_type = "dir"
#' )
#'
#' unlink(tmpdir, recursive = TRUE)
copy_if_not_already_exist <- function(
    from,
    to,
    copy_type = c("file", "dir"),
    quiet = FALSE
){
  # verify input
  copy_type <- match.arg(copy_type)
  
  # verify files/dir is already present
  already_present <- file.exists(to)
  
  if (already_present) {
    if (!quiet){
      cli_alert_info(
        paste(
          "{to} already present in quarto project.",
          "Using it for compil."
        )
      )
    }
    return(NULL)
  }
  
  if (!already_present){
    if (copy_type == "dir"){
      if (!dir.exists(dirname(to))){
        dir.create(
          dirname(to),
          recursive = TRUE
        )
        to_copied_path <- dirname(to)
      }
      
      file.copy(
        from = from,
        to = dirname(to),
        recursive = TRUE
      )
    } else {
      file.copy(
        from = from,
        to = to
      )
      to_copied_path <- to
    }
  }
  # return path that has been created
  return(to_copied_path)
}
