# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' create_template_html
#' 
#' Create a template html with ThinkR styling
#' 
#' @param path_to_qmd character. Path to the qmd template to be rendered in thinkridentity-revealjs
#' @param output_dir character. Path to html output dir
#' @param output_file character. Name of the output html template
#' @param temp_dir character. Path to the temp_dir where template will be rendered
#' 
#' @importFrom quarto quarto_render
#' @importFrom utils download.file unzip
#'
#' @return character. Path to the html template
#' 
#' @export
#' @examples
#' # create temp dir
#' temp_dir <- tempfile(pattern = "template")
#' 
#' # create html template
#' path_to_html_template <- create_template_html(
#'   path_to_qmd = system.file("template.qmd", package = "nq1h"),
#'   output_dir = temp_dir,
#'   output_file = "complete_course.html"
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
create_template_html <- function(
  path_to_qmd,
  output_dir,
  output_file,
  temp_dir = tempfile(pattern = "template")
  ){
    
  # set qmd file name base on html output name
  output_file_qmd <- gsub("\\.html", "\\.qmd", output_file)
  
  # copy qmd template to temp_dir with new name
  if (!file.exists(temp_dir)){
    dir.create(temp_dir)
  }
  
  file.copy(
    from = path_to_qmd,
    to = file.path(
      temp_dir,
      output_file_qmd)
    )
  
  # download quakr _extensions from GitHub to temp_dir
  download.file(
    url = "https://github.com/ThinkR-open/quakr/archive/refs/heads/main.zip",
    destfile = file.path(temp_dir, "quakr.zip"),
    quiet = TRUE
    )

  if (!file.exists(file.path(temp_dir, "quakr.zip"))){
    stop("Thinkr-open/quakr zip was not properly downloaded.")
  }
    
  unzip(
    zipfile = file.path(temp_dir, "quakr.zip"),
    exdir = file.path(temp_dir, "quakr")
    )
  
  dir.create(file.path(temp_dir, "_extensions/"))
  
  file.copy(
    from = file.path(temp_dir, "quakr", "quakr-main", "_extensions/."),
    to = file.path(temp_dir, "_extensions"),
    recursive = TRUE)
  
  # render template with ThinkR theme and img/ folder output
  img_dir <- file.path(
      gsub("\\.html", "_img", output_file),
      "template_img"
    )
  
  quarto_render(
    input = file.path(temp_dir, output_file_qmd),
    output_format = "thinkridentity-revealjs",
    quiet = FALSE)
  
  # copy output html and companion folders to output_dir
  files_to_copy <- c(
    "html" = file.path(temp_dir, output_file),
    "lib_folder" = file.path(temp_dir, gsub("\\.html", "_files", output_file)),
    "ext_folder" = file.path(temp_dir, "_extensions")
  )
  
  if (!file.exists(output_dir)){
    dir.create(output_dir)
  }
  
  file.copy(
    from = files_to_copy,
    to = output_dir,
    recursive = TRUE
  )
  
  # remove temp_dir
  unlink(temp_dir, recursive = TRUE)
  
  # return path to html template
  return(file.path(output_dir, output_file))
  
}
