# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' create_template_html
#' 
#' Create a template html with ThinkR styling
#' 
#' @param path_to_qmd character. Path to the qmd template to be rendered in html
#' @param output_dir character. Path where files and html will be generated
#' @param output_file character. Name of the output html template
#' 
#' @importFrom quarto quarto_render
#'
#' @return character. Path to the html template
#' 
#' @export
#' @examples
#' # create temp dir
#' temp_dir <- tempfile(pattern = "template")
#' 
#' # create html template
#' path_to_html_template <- create_template_html(
#'   path_to_qmd = system.file("template.qmd", package = "nq1h"),
#'   output_dir = temp_dir,
#'   output_file = "complete_course.html"
#' )
#' 
#' # clean up
#' unlink(temp_dir, recursive = TRUE)
create_template_html <- function(
  path_to_qmd,
  output_dir,
  output_file
  ){
    
  # copy qmd template to output dir with new name
  if (!file.exists(output_dir)){
    dir.create(output_dir)
  }
  
  output_file_qmd <- gsub("\\.html", "\\.qmd", output_file)
  
  file.copy(
    from = path_to_qmd,
    to = file.path(
      output_dir,
      output_file_qmd)
    )
  
  # copy quakr _extension in output dir
  # `quarto add` not defined in {quarto} yet
  file.copy(
    from = system.file("_extensions", package = "nq1h"),
    to = output_dir,
    recursive = TRUE
  )
  
  # render template with ThinkR theme and img/ folder output
  img_dir <- file.path(
      gsub("\\.html", "_img", output_file),
      "template_img"
    )
  
  quarto_render(
    input = file.path(output_dir, output_file_qmd),
    pandoc_args = paste0("--extract-media=", img_dir),
    quiet = TRUE)
  
  # remove qmd file from output dir
  unlink(file.path(output_dir,
                   output_file_qmd))
  
  # return path to html template
  return(file.path(output_dir, output_file))
  
}
