# WARNING - Generated by {fusen} from /dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' extract_html_slides
#'
#' Extract slide content from multiple html
#'
#' @param vec_html_path character. The vector of path to individual html files
#'
#' @importFrom tools file_ext
#' @importFrom rvest read_html html_elements html_children
#' @importFrom htmltools HTML
#'
#' @return HTML. The HTML slide content of all html files combined together.
#'
#' @export
#' @examples
#' # list html files
#' courses_path <- system.file(
#'   "courses",
#'   package = "nq1h"
#' )
#' 
#' htmls <- list.files(
#'   path = courses_path,
#'   full.names = TRUE,
#'   pattern = "html$"
#' )
#' 
#' html_slide_content <- extract_html_slides(vec_html_path = htmls)
extract_html_slides <- function(
    vec_html_path) {
  # verify path are html files
  not_all_files_are_html <- any(
    file_ext(vec_html_path) != "html"
  )
  if (isTRUE(not_all_files_are_html)) {
    stop("Some of the input files are not html files.")
  }
  
  # extract all slides elements
  list_html_slides <- lapply(
    X = vec_html_path,
    FUN = \(html_path) {
      html_path |>
        read_html() |>
        html_elements(".slides") |>
        html_children() |>
        as.character()
    }
  )
  
  # rename 1st slide to avoid duplicated title-slide ids
  list_html_slides <- lapply(
    X = seq_along(list_html_slides),
    FUN = \(slide_number) {
      gsub(
        pattern = "title-slide",
        replacement = paste0("title-slide-", as.character(slide_number)),
        x = list_html_slides[[slide_number]]
      )
    }
  )
  
  # compile all slides content into a single HTML text
  html_content <- list_html_slides |>
    unlist() |>
    paste0(collapse = "\n") |>
    HTML()
  
  return(html_content)
}
