# WARNING - Generated by {fusen} from dev/flat_compile_qmd_course.Rmd: do not edit by hand

#' Render a qmd course to html 
#' 
#' Render a single qmd file to html with image folder.
#' 
#' @param qmd character. Path to the qmd file to render
#' @param img_root_dir character. Path to the main image folder to extract media to
#' 
#' @importFrom quarto quarto_render
#' @importFrom cli cli_alert_danger
#' 
#' @return logical. TRUE if rendering succeeded, FALSE otherwise. Side effect : render qmd as html
#' 
#' @export
#' @examples
#' # create a temp dir with qmd
#' temp_dir <- tempfile(pattern = "render")
#'
#' dir.create(
#'   path = file.path(temp_dir, "img"),
#'   recursive = TRUE
#' )
#'
#' file.copy(
#'   from = system.file("courses", "M01", "M01S01", "C01-qmd1_for_test.qmd", package = "squash"),
#'   to = temp_dir
#' )
#'
#' file.copy(
#'   from = system.file("courses", "M01", "M01S01", "img", "logo_1.png", package = "squash"),
#'   to = file.path(temp_dir, "img")
#' )
#'
#' # render qmd
#' is_rendered <- render_single_qmd(
#'   qmd = file.path(temp_dir, "C01-qmd1_for_test.qmd"),
#'   img_root_dir = file.path(temp_dir, "image_folder")
#' )
#'
#' # clean temp dir
#' unlink(temp_dir, recursive = TRUE)
render_single_qmd <- function(
    qmd,
    img_root_dir = "img"
) {
  # set image sub-folder name
  chapter <- dirname(qmd)
  
  img_dir <- file.path(
    img_root_dir,
    paste0(basename(chapter), "_img")
  )
  
  # try rendering qmd and warn user if successful / fail
  tryCatch(
    expr = {
      quarto_render(
        input = qmd,
        quiet = TRUE,
        # use revealjs parameter to make a copy of img dir
        # use compil quarto profile to not add logo/bg and footer from quakr
        pandoc_args = c(paste0("--extract-media=", img_dir),
                        "--profile=compil")
      )
      return(TRUE)
    },
    error = \(error_message) {
      cli_alert_danger("Fail to render {qmd}, cleaning and existing")
      
      # throw an error with original error message
      return(FALSE)
    }
  )
}
